// <auto-generated />
using AutomationtestAPIs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutomationtestAPIs.Migrations
{
    [DbContext(typeof(LoginContext))]
    [Migration("20221122071022_initial1")]
    partial class initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutomationtestAPIs.Models.Login", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("AutomationtestAPIs.Models.StoryTrackerDB", b =>
                {
                    b.Property<string>("Ticket_no")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bugs_count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code_deviation_count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code_reviewer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("End_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serial_no")
                        .HasColumnType("int");

                    b.Property<string>("Start_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Story_point")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ticket_no");

                    b.ToTable("StoryTrackerDBs");
                });
#pragma warning restore 612, 618
        }
    }
}
